export const COLOR_BLUE ="#124DBD"
export const COLOR_LIGHT_BLUE = "#9EBEF2"
export const COLOR_DARK_BLUE = "#1c4b98"
export const COLOR_WHITE = "#ffffff"
export const COLOR_GRAY = "#E6E8EB"
export const COLOR_DARK_GRAY = "#3e424a"